package com.project.backend.enums;

public enum ExpenseCategory {
    FOOD,
    TRANSPORTATION,
    HOUSING,
    UTILITIES,
    HEALTHCARE,
    ENTERTAINMENT,
    EDUCATION,
    SHOPPING,
    PERSONAL_CARE,
    INVESTMENTS,
    TRAVEL,
    GIFTS_DONATIONS,
    INSURANCE,
    DEBT_REPAYMENT,
    CHILDCARE,
    PET_CARE,
    SUBSCRIPTIONS,
    TAXES,
    MAINTENANCE,
    COMMUNICATION,
    OTHER
}
